notifications:
  email:
    recipients:
     - romesh69@hotmail.com

    on_success: never
    on_failure: change

# safelist
branches:
  only:
  - master

language: java
sudo: required
services:
  - docker

# Build the Java app
jdk:
  - oraclejdk8
script: mvn clean install

#Build the Docker image and push to registry
after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker build -t rselvanathan/romcharm-rest:latest .
  - docker push rselvanathan/romcharm-rest


